import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/hotelsearchresults">Hotelsearchresults</Link>
        </li>
        <li>
          <Link to="/hotelsearchresultsone">HotelsearchresultsOne</Link>
        </li>
        <li>
          <Link to="/hotelsearchresultstwo">HotelsearchresultsTwo</Link>
        </li>
        <li>
          <Link to="/hotelsearchresultsthree">HotelsearchresultsThree</Link>
        </li>
        <li>
          <Link to="/additionalinformation">AdditionalInformation</Link>
        </li>
        <li>
          <Link to="/paymentmethodsbankaccount">PaymentMethodsBankAccount</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
